spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weather_db
    username: adi
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

openweather:
  api:
    key: c396833a8d0aa9ad7157d375cfb83bac
