spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weather_db
    username: xxx
    password: xxx
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

openweather:
  api:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
